FROM python:3-buster

RUN useradd --shell /bin/bash user --create-home -d /home/user/
WORKDIR /home/user/

COPY . .
RUN pip install --no-cache-dir redis==3.3.11 numpy==1.16.2 nltk==3.4.5
WORKDIR src/

RUN chown -R user:user /home/user
USER user

CMD [ "python", "main.py" ]

