FROM python:3-buster

RUN useradd --shell /bin/bash user --create-home -d /home/user/
WORKDIR /home/user/

COPY . .
RUN pip install --no-cache-dir cython==0.29.14 && pip install --no-cache-dir redis==3.3.11 mongoengine==0.18.2 pyfasttext==0.4.6 nltk==3.4.5

RUN chown -R user:user /home/user
USER user

CMD [ "python", "main.py" ]

