FROM python:3-buster

RUN useradd --shell /bin/bash user --create-home -d /home/user/
WORKDIR /home/user/

COPY . .
RUN pip install --no-cache-dir numpy==1.16.2 && pip install --no-cache-dir redis==3.3.11 mongoengine==0.18.2 \
   nltk==3.4.5 scikit-learn==0.22 django==3.0

RUN chown -R user:user /home/user
USER user

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]




















